server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie-ribbon
#  cloud:
#    config:
#      fail-fast: true
#      discovery:
#        enabled: true
#        service-id: 这里设置配置文件服务器的地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true